name: Build & Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup MSVC
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Configure
        run: cmake --preset ci

      - name: Build Release
        run: cmake --build build/ci --config Release

      - name: Run tests
        run: ctest --test-dir build/ci -C Release --output-on-failure

      - name: Prepare artifact
        run: |
          mkdir artifact\WavTool\src
          mkdir artifact\WavTool\src\tests
          copy *.h artifact\WavTool\src\
          copy *.cpp artifact\WavTool\src\
          copy CMakeLists.txt artifact\WavTool\src\
          copy CMakePresets.json artifact\WavTool\src\
          copy README.md artifact\WavTool\
          copy tests\* artifact\WavTool\src\tests\
          copy build\ci\wav_tool.exe artifact\WavTool\
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: WavTool-Release
          path: artifact/WavTool/
          retention-days: 90
